/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.8
<<<<<<< HEAD
<<<<<<< HEAD:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/kullaniciliste_jsp.java
 * Generated at: 2023-07-26 12:05:30 UTC
=======
 * Generated at: 2023-07-27 09:00:01 UTC
>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/engellitiptanim_jsp.java
=======
<<<<<<<< HEAD:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/kullaniciliste_jsp.java
 * Generated at: 2023-07-26 12:05:30 UTC
========
 * Generated at: 2023-07-27 09:00:01 UTC
>>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/engellitiptanim_jsp.java
>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.adminpanel;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import jakarta.servlet.http.HttpSession;
import com.example.example.DataBase.Personel;
<<<<<<< HEAD
<<<<<<< HEAD:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/kullaniciliste_jsp.java
import com.example.example.DataBase.Personel.RoleUtils;
=======
import com.example.example.DataBase.Disabled;
>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/engellitiptanim_jsp.java
=======
<<<<<<<< HEAD:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/kullaniciliste_jsp.java
import com.example.example.DataBase.Personel.RoleUtils;
========
import com.example.example.DataBase.Disabled;
>>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/engellitiptanim_jsp.java
>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb
import java.util.List;
import com.example.example.DataBase.Rol;
import java.util.List;

public final class engellitiptanim_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
<<<<<<< HEAD
<<<<<<< HEAD:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/kullaniciliste_jsp.java
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/adminpanel/sidebar.jsp", Long.valueOf(1690355654116L));
=======
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/adminpanel/navbar.jsp", Long.valueOf(1690374099839L));
    _jspx_dependants.put("/adminpanel/sidebar.jsp", Long.valueOf(1690374102181L));
>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/engellitiptanim_jsp.java
=======
<<<<<<<< HEAD:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/kullaniciliste_jsp.java
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/adminpanel/sidebar.jsp", Long.valueOf(1690355654116L));
========
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/adminpanel/navbar.jsp", Long.valueOf(1690374099839L));
    _jspx_dependants.put("/adminpanel/sidebar.jsp", Long.valueOf(1690374102181L));
>>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/engellitiptanim_jsp.java
>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("jakarta.servlet.http.HttpSession");
<<<<<<< HEAD
<<<<<<< HEAD:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/kullaniciliste_jsp.java
    _jspx_imports_classes.add("com.example.example.DataBase.Personel.RoleUtils");
=======
    _jspx_imports_classes.add("com.example.example.DataBase.Disabled");
>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/engellitiptanim_jsp.java
=======
<<<<<<<< HEAD:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/kullaniciliste_jsp.java
    _jspx_imports_classes.add("com.example.example.DataBase.Personel.RoleUtils");
========
    _jspx_imports_classes.add("com.example.example.DataBase.Disabled");
>>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/engellitiptanim_jsp.java
>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.example.example.DataBase.Personel");
    _jspx_imports_classes.add("com.example.example.DataBase.Rol");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");



List<Disabled> disabled = Disabled.getAll();
/*
  List<Personel> users = Personel.getAllUserInfo();

<<<<<<< HEAD
<<<<<<< HEAD:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/kullaniciliste_jsp.java
=======
  
>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/engellitiptanim_jsp.java
=======
<<<<<<<< HEAD:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/kullaniciliste_jsp.java
========
  
>>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/engellitiptanim_jsp.java
>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb
HttpSession userSession = request.getSession();
String roleName = "Role_Kullanıcı_Listele";

if (!RoleUtils.hasRole(userSession, roleName)) {
    response.sendRedirect("../Error/Error.html");
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <title>Gebze Belediyesi | Yönetim Paneli</title>\r\n");
      out.write("  <!-- Tell the browser to be responsive to screen width -->\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <!-- Font Awesome -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plugins/fontawesome-free/css/all.min.css\">\r\n");
      out.write("  <!-- Ionicons -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plugins/datatables-bs4/css/dataTables.bootstrap4.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plugins/datatables-bs4/css/dataTables.bootstrap4.min.css\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- Tempusdominus Bbootstrap 4 -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css\">\r\n");
      out.write("  <!-- iCheck -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plugins/icheck-bootstrap/icheck-bootstrap.min.css\">\r\n");
      out.write("  <!-- JQVMap -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plugins/jqvmap/jqvmap.min.css\">\r\n");
      out.write("  <!-- Theme style -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"dist/css/adminlte.min.css\">\r\n");
      out.write("  <!-- overlayScrollbars -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plugins/overlayScrollbars/css/OverlayScrollbars.min.css\">\r\n");
      out.write("  <!-- Daterange picker -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plugins/daterangepicker/daterangepicker.css\">\r\n");
      out.write("  <!-- summernote -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"plugins/summernote/summernote-bs4.css\">\r\n");
      out.write("  <!-- Google Font: Source Sans Pro -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700\" rel=\"stylesheet\">\r\n");
      out.write("  <style>\r\n");
      out.write("  		.custom-datatable2{\r\n");
      out.write("  		background-color:  #fafafa;\r\n");
      out.write("	  		position: relative;\r\n");
      out.write("	    padding: 40px; /* Arkaya gölge için içeriği itin */\r\n");
      out.write("	    border-radius: 10px; /* Köşeleri keskin olmaktan çıkarın */\r\n");
      out.write("	    box-shadow: 0 2px 6px rgba(0, 0, 0, 0.4); /* Gölgeli efekti ekle */\r\n");
      out.write("	    \r\n");
      out.write("	    margin-left: 30px;\r\n");
      out.write("	    margin-right: 30px;\r\n");
      out.write("  		}\r\n");
      out.write("	  .pagination .page-item.active .page-link {\r\n");
      out.write("	    background-color: #17a2b8; /* Kırmızı renk (#ff0000) olarak ayarlandı */\r\n");
      out.write("	    border-color: #17a2b8; /* Kenarlık rengi de kırmızı yapılıyor */\r\n");
      out.write("	    color: #fff !important; /* Metin rengi beyaz (#fff) olarak ayarlandı */\r\n");
      out.write("	  }\r\n");
      out.write("    /* DataTables stil düzenlemesi */\r\n");
      out.write("    .dataTables_wrapper {\r\n");
      out.write("      position: relative;\r\n");
      out.write("      padding: 20px; /* Arkaya gölge için içeriği itin */\r\n");
      out.write("      border-radius: 10px; /* Köşeleri keskin olmaktan çıkarın */\r\n");
      out.write("      box-shadow: 0 2px 6px rgba(0, 0, 0, 0.2); /* Gölgeli efekti ekle */\r\n");
      out.write("    }\r\n");
      out.write("    .custom-datatable {\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    padding: 40px; /* Arkaya gölge için içeriği itin */\r\n");
      out.write("    border-radius: 10px; /* Köşeleri keskin olmaktan çıkarın */\r\n");
      out.write("    box-shadow: 0 2px 6px rgba(0, 0, 0, 0.4); /* Gölgeli efekti ekle */\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("    margin-left: 30px;\r\n");
      out.write("    margin-right: 30px; /* Sol boşluk bırakmayın */\r\n");
      out.write("    \r\n");
      out.write("  }\r\n");
      out.write("  	.custom-datatable td {\r\n");
      out.write("	    font-size: 14px; /* Metin boyutunu ayarlayın */\r\n");
      out.write("	    font-family: Arial, sans-serif; /* Yazı tipini belirleyin */\r\n");
      out.write("	   	background-color: #f2f2f2; /* Arka plan rengini ayarlayın */\r\n");
      out.write("    	color: #333; /* Metin rengini ayarlayın */\r\n");
      out.write("  }\r\n");
      out.write("  	.custom-datatable th {\r\n");
      out.write("  		padding: 10px; /* Arkaya gölge için içeriği itin */\r\n");
      out.write("	    /* Köşeleri keskin olmaktan çıkarın */\r\n");
      out.write("	   \r\n");
      out.write("  	\r\n");
      out.write("	    font-size: 14px;\r\n");
      out.write("	    font-weight: bold;\r\n");
      out.write("	     /* Metin boyutunu ayarlayın */\r\n");
      out.write("	    font-family: Arial, sans-serif; /* Yazı tipini belirleyin */\r\n");
      out.write("	   \r\n");
      out.write("  }\r\n");
      out.write("  	.custom-datatable2 h3.card-title {\r\n");
      out.write("  	\r\n");
      out.write("	  font-size: 24px; /* Yazı boyutunu istediğiniz gibi ayarlayın */\r\n");
      out.write("	  font-weight: bold;\r\n");
      out.write("	  font-family: Arial, sans-serif; /* Kalın yazı tipi */\r\n");
      out.write("	  text-align: center; /* Yazıyı ortala */\r\n");
      out.write("	  margin-bottom: 20px; /* Aşağıya boşluk bırakın */\r\n");
      out.write("}	\r\n");
      out.write("	.card-info {\r\n");
      out.write("      background-color:  #fafafa; /* Turkuaz rengi (#17a2b8) olarak ayarlandı */\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      box-shadow: 0 2px 6px rgba(0, 0, 0, 0.4); /* Gölgeli efekt eklemek için */\r\n");
      out.write("      margin: 30px; /* Kenar boşlukları */\r\n");
      out.write("      padding: 40px; /* İçerikten içeri boşluk bırakmak için */\r\n");
      out.write("    }\r\n");
      out.write("	.koyu-yazi {\r\n");
      out.write("  color: #000000; /* Siyah rengin hexadecimal kodu */\r\n");
      out.write("  /* Diğer stil özelliklerini burada belirtebilirsiniz */\r\n");
      out.write("}\r\n");
      out.write("    \r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"hold-transition sidebar-mini layout-fixed\">\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Navbar -->\r\n");
      out.write("  ");
      out.write("<nav class=\"main-header navbar navbar-expand navbar-white navbar-light\">\r\n");
      out.write("    <!-- Left navbar links -->\r\n");
      out.write("    <ul class=\"navbar-nav\">\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" data-widget=\"pushmenu\" href=\"#\" role=\"button\"><i class=\"fas fa-bars\"></i></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-sm-inline-block\">\r\n");
      out.write("        <a href=\"anasayfa.jsp\" class=\"nav-link\">Anasayfa</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <!-- SEARCH FORM -->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- Right navbar links -->\r\n");
      out.write("    \r\n");
      out.write("  </nav>");
      out.write("\r\n");
      out.write("  <!-- /.navbar -->\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("  /* Sidebardaki \"Anasayfa\", \"İşlemlerim\", \"Yönetici İşlemleri\" ve \"Raporlar\" başlıklarının yazı rengini ve arka plan rengini belirgin hale getir */\r\n");
      out.write("  \r\n");
      out.write("  #islemlerim.nav-link,\r\n");
      out.write("  #yonetici.nav-link,\r\n");
      out.write("  #rapor.nav-link {\r\n");
      out.write("    color: #fff; /* Yazı rengini istediğiniz renk koduyla değiştirebilirsiniz */\r\n");
      out.write("    background-color: #494949; /* Arka plan rengini istediğiniz renk koduyla değiştirebilirsiniz */\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- Main Sidebar Container -->\r\n");
      out.write("  <aside class=\"main-sidebar sidebar-dark-primary elevation-4\">\r\n");
      out.write("    <!-- Brand Logo -->\r\n");
      out.write("    <a href=\"anasayfa.jsp\" class=\"brand-link\">\r\n");
      out.write("      <img src=\"1111.png\" alt=\"AdminLTE Logo\" class=\"brand-image img-circle elevation-3\"\r\n");
      out.write("           style=\"opacity: 10\">\r\n");
      out.write("      <span class=\"brand-text font-weight-light\">Gebze Belediyesi</span>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <!-- Sidebar -->\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("      <!-- Sidebar user panel (optional) -->\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("      <!-- Sidebar Menu -->\r\n");
      out.write("      <nav class=\"mt-2\">\r\n");
      out.write("        <ul class=\"nav nav-pills nav-sidebar flex-column\" data-widget=\"treeview\" role=\"menu\" data-accordion=\"false\">\r\n");
      out.write("          <!-- Add icons to the links using the .nav-icon class\r\n");
      out.write("               with font-awesome or any other icon font library -->\r\n");
      out.write("               <li class=\"nav-item\">\r\n");
      out.write("                <a id=\"anasayfa\" href=\"anasayfa.jsp\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"fas fa-home\"></i>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Anasayfa\r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("          <li class=\"nav-item has-treeview\">\r\n");
      out.write("            <a id=\"islemlerim\" href=\"#\" class=\"nav-link\">\r\n");
      out.write("              <i class=\"fa fa-check-square\" aria-hidden=\"true\"></i>\r\n");
      out.write("\r\n");
      out.write("              <p>\r\n");
      out.write("                İşlemlerim\r\n");
      out.write("                <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("              </p>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"nav nav-treeview\">\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item has-treeview\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"fas fa-user\"></i>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Müracaat\r\n");
      out.write("                    <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"nav nav-treeview\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"geneltakip.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Genel Takip</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"muracaatgir.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Müracaat Girişi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"muracaatliste.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Müracaat Listesi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"egitimliste.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Eğitim Listesi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"nav nav-treeview\">\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item has-treeview\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"fa fa-address-book\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Tutanak\r\n");
      out.write("                    <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"nav nav-treeview\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"tutanakgir.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Tutanak Girişi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"tutanaklist.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Tutanak Listesi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"nav nav-treeview\">\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item has-treeview\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"fa fa-address-book\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Yardım Kararı\r\n");
      out.write("                    <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"nav nav-treeview\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"yardimkararlist.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Yardım Karar Listesi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"yardimkararlistozel.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Yardım Liste Özel</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"topyardim.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Toplu Yardım Yükleme</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav nav-treeview\">\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item has-treeview\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"fa fa-address-book\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Aşevi\r\n");
      out.write("                    <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"nav nav-treeview\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"asevigir.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Aşevi Bilgi Girişi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"asevilist.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Aşevi Bilgi Listesi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav nav-treeview\">\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item has-treeview\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"fa fa-wheelchair\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Engelli Bilgisi\r\n");
      out.write("                    <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"nav nav-treeview\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"engellilist.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Engelli Bilgi Listesi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"engelliarac.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Engelli Araç Bilgi Listesi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav nav-treeview\">\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item has-treeview\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"fa fa-bars\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Aile Yakınlık Bilgisi\r\n");
      out.write("                    <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"nav nav-treeview\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"aileyakinlik.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Aile Yakınlık Bilgi Listesi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item has-treeview\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"fa fa-graduation-cap\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Stok\r\n");
      out.write("                    <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"nav nav-treeview\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"stokgir.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Stok Girişi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"stoklist.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Stok Listesi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item has-treeview\">\r\n");
      out.write("            <a id=\"yonetici\" href=\"#\" class=\"nav-link\">\r\n");
      out.write("              <i class=\"fa fa-user-plus\" aria-hidden=\"true\"></i>\r\n");
      out.write("              <p>\r\n");
      out.write("                Yönetici İşlemleri\r\n");
      out.write("                <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("              </p>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"nav nav-treeview\">\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item has-treeview\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"fas fa-user\"></i>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Kullanıcı\r\n");
      out.write("                    <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"nav nav-treeview\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"kullaniciyukle.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Kullanıcı Yükle</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"kullaniciliste.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Kullanıcı Listele</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"nav nav-treeview\">\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item has-treeview\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"fa fa-address-book\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Bölge\r\n");
      out.write("                    <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"nav nav-treeview\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"./bolgegiris.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Bölge Girişi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"bolgetanimlama.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Bölge Tanımlama</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"nav nav-treeview\">\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item has-treeview\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"fa fa-address-book\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Mahalle\r\n");
      out.write("                    <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"nav nav-treeview\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"mahallegir.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Mahalle Girişi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"./mahallelist.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Mahalle Listele</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav nav-treeview\">\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item has-treeview\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"fa fa-address-book\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Cadde/Sokak\r\n");
      out.write("                    <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"nav nav-treeview\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"./caddegir.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Cadde/Sokak Girişi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"./caddelist.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Cadde/Sokak Listesi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav nav-treeview\">\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item has-treeview\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"fa fa-graduation-cap\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Eğitim\r\n");
      out.write("                    <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"nav nav-treeview\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"./okulgiris.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Okul Girişi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"./okullist.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Okul Listesi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav nav-treeview\">\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item has-treeview\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"fa fa-bars\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Diğer Tanımlar\r\n");
      out.write("                    <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"nav nav-treeview\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"./cekmecetanim.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Çekmece Tanımlama</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"./meslektanimlama.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Meslek Tanımlama</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"./yakinlik.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Yakınlık Tanımlama</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"./tutanakdurumtanimlama.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Tutanak Durum Tanımlama</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav nav-treeview\">\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item has-treeview\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"fa fa-info-circle\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Yardım Parametreleri\r\n");
      out.write("                    <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"nav nav-treeview\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"./yardimtipi.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Yardım Tipi Tanımlama</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"./yardimalttip.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Yardım Alt Tip Tanımlama</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"./talepedilen.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Talep Edilen Yardım Tipi</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"./tanimlama.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Tanımlama</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav nav-treeview\">\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item has-treeview\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"fa fa-wheelchair\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Engelli Tipleri Girişi\r\n");
      out.write("                    <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"nav nav-treeview\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"./engellitiptanim.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Engelli Tipi Tanımlama</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"./engellialttip.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Engelli Alt Tipi Tanımlama</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"./yonkurum.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Yönlendirilen Kurum</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"./yonaltkurum.jsp\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                      <p>Yönlendirilen Alt Kurum</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("          <li class=\"nav-item has-treeview\">\r\n");
      out.write("            <a id=\"rapor\" href=\"#\" class=\"nav-link\">\r\n");
      out.write("              <i class=\"fa fa-book\" aria-hidden=\"true\"></i>\r\n");
      out.write("\r\n");
      out.write("              <p>\r\n");
      out.write("                Raporlar\r\n");
      out.write("                <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("              </p>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"nav nav-treeview\">\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a href=\"./muracaatrapor.jsp\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                  <p>Müracaat Raporu</p>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a href=\"./tutanakrapor.jsp\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                  <p>Tutanak Raporu</p>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a href=\"./yardimkarara.jsp\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                  <p>Yardım Karar Raporu</p>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a href=\"./yardimkararyillikr.jsp\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                  <p>Yardım Karar Yıllık Raporu</p>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("        \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("        </ul>\r\n");
      out.write("        \r\n");
      out.write("      </nav>\r\n");
      out.write("      <!-- /.sidebar-menu -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.sidebar -->\r\n");
      out.write("  </aside>\r\n");
      out.write("\r\n");
      out.write("  <!-- Content Wrapper. Contains page content -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Content Wrapper. Contains page content -->\r\n");
      out.write("  <div class=\"content-wrapper\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- /.content-header -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Main content -->\r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <!-- Small boxes (Stat box) -->\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-12\">\r\n");
      out.write("                <div class=\"card card-info\">\r\n");
      out.write("                    <div class=\"card-header d-flex justify-content-center\"\">\r\n");
      out.write("                        <h3 class=\"card-title\">Engelli Tip Tanımlama</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                    <!-- form başlangıcı -->\r\n");
      out.write("                    <form role=\"form\" action=\"disabledType\" method=\"post\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                          <div class=\"row\">\r\n");
      out.write("                          	\r\n");
      out.write("                          	<div class=\"col-sm-4\">\r\n");
      out.write("                              <div class=\"form-group text-center\">\r\n");
      out.write("                                <label>Engelli Tip Adı</label>\r\n");
      out.write("                                <div class=\"input-group\"> <!-- input alanını düzenlemek için input-group kullanıyoruz -->\r\n");
      out.write("				                  <input type=\"text\" class=\"form-control\" name=\"disabledname\" required>\r\n");
      out.write("				                  <div class=\"input-group-append\"> <!-- Butonu input alanına eklemek için input-group-append kullanıyoruz -->\r\n");
      out.write("				                    <button type=\"submit\" class=\"btn btn-info\">Ekle</button>\r\n");
      out.write("				                  </div>\r\n");
      out.write("				                </div>\r\n");
      out.write("                                                                   \r\n");
      out.write("                               \r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>  \r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- form sonu -->  \r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Modal -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.row -->\r\n");
      out.write("        <!-- Main row -->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"col-12\">\r\n");
      out.write("		            <div class=\"card custom-datatable2\">\r\n");
      out.write("		                <div class=\"card-header d-flex justify-content-center\">\r\n");
      out.write("		                    <h3 class=\"card-title font-weight-bold\">ENGELLİ TİP LİSTESİ</h3>                	                \r\n");
      out.write("						</div><!-- /.card-header -->\r\n");
      out.write("		                <div class=\"card-body custom-datatable\">\r\n");
      out.write("		                  <table id=\"example2\" class=\"table table-bordered table-hover\">\r\n");
      out.write("		                    <thead>\r\n");
      out.write("		                    <tr>\r\n");
      out.write("		                        <th>Engelli Tip Kodu</th>\r\n");
      out.write("		                        <th>Engelli Tip Adı</th>\r\n");
      out.write("		                        <th></th>\r\n");
<<<<<<< HEAD
<<<<<<< HEAD:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/kullaniciliste_jsp.java
=======
<<<<<<<< HEAD:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/kullaniciliste_jsp.java
>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb
      out.write("<<<<<<< HEAD\r\n");
      out.write("		                        <th></th>\r\n");
      out.write("		                        \r\n");
      out.write("		\r\n");
      out.write("=======\r\n");
      out.write("                            <th></th>\r\n");
      out.write(">>>>>>> 7fd0b9eaae8ed87a85731764508a663b983da08b\r\n");
      out.write("		                        \r\n");
      out.write("		                        \r\n");
<<<<<<< HEAD
=======
      out.write("		                        <th></th>   \r\n");
>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/engellitiptanim_jsp.java
=======
========
      out.write("		                        <th></th>   \r\n");
>>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb:.metadata/.plugins/org.eclipse.wst.server.core/tmp1/work/Catalina/localhost/basic-webapp/org/apache/jsp/adminpanel/engellitiptanim_jsp.java
>>>>>>> 4a2fe51223c32e1c3057c4eaefb8a3e9baf8d9cb
      out.write("		                    </tr>\r\n");
      out.write("		                    </thead>\r\n");
      out.write("		                    <tbody>  \r\n");
      out.write("		                    ");
 for(Disabled disa : disabled){
      out.write("      \r\n");
      out.write("		                    <tr>\r\n");
      out.write("		                      <td>");
      out.print( disa.getDisabledID() );
      out.write("</td>\r\n");
      out.write("		                      <td> ");
      out.print( disa.getDisabledName() );
      out.write("</td> \r\n");
      out.write("		                      <td>\r\n");
      out.write("								  <a href=\"engellitipduzenle.jsp?ID=");
      out.print( disa.getDisabledID());
      out.write("\">\r\n");
      out.write("								    	<i class=\"fa fa-cog\" style=\"font-size: 20px; color:#17a2b8; cursor: pointer;\"></i>\r\n");
      out.write("								  </a>\r\n");
      out.write("							  </td>\r\n");
      out.write("							  <td>\r\n");
      out.write("								  <i class=\"fa fa-trash\" style=\"font-size: 20px; color: #17a2b8; cursor: pointer;\" onclick=\"confirmDelete()\"></i>\r\n");
      out.write("							  </td>		\r\n");
      out.write("		                    </tr>\r\n");
      out.write("		                    </tbody>\r\n");
      out.write("		                    ");
 }
      out.write("	                    \r\n");
      out.write("		                  </table>\r\n");
      out.write("		                </div>\r\n");
      out.write("		                <!-- /.card-body -->\r\n");
      out.write("		              </div>\r\n");
      out.write("		            <!-- /.card -->\r\n");
      out.write("		          </div>\r\n");
      out.write("          <!-- Modal -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.row (main row) -->\r\n");
      out.write("      </div><!-- /.container-fluid -->    \r\n");
      out.write("    <!-- /.content -->\r\n");
      out.write("  </div>  \r\n");
      out.write("  <!-- /.content-wrapper -->\r\n");
      out.write("  <footer class=\"main-footer\">\r\n");
      out.write("    <strong><a href=\"https://www.gebze.bel.tr/\">Gebze Belediyesi  </a></strong>  \r\n");
      out.write("    <div class=\"float-right d-none d-sm-inline-block\">\r\n");
      out.write("      <b>2023</b>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("  <!-- Control Sidebar -->\r\n");
      out.write("  <aside class=\"control-sidebar control-sidebar-dark\">\r\n");
      out.write("    <!-- Control sidebar content goes here -->\r\n");
      out.write("  </aside>\r\n");
      out.write("  <!-- /.control-sidebar -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ./wrapper -->\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("<!-- jQuery UI 1.11.4 -->\r\n");
      out.write("<script src=\"plugins/jquery-ui/jquery-ui.min.js\"></script>\r\n");
      out.write("<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->\r\n");
      out.write("<script>\r\n");
      out.write("  $.widget.bridge('uibutton', $.ui.button)\r\n");
      out.write("</script>\r\n");
      out.write("<!-- Bootstrap 4 -->\r\n");
      out.write("<script src=\"plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<!-- ChartJS -->\r\n");
      out.write("<script src=\"//cdn.datatables.net/plug-ins/1.13.5/i18n/tr.json\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"plugins/chart.js/Chart.min.js\"></script>\r\n");
      out.write("<!-- Sparkline -->\r\n");
      out.write("<script src=\"plugins/sparklines/sparkline.js\"></script>\r\n");
      out.write("<!-- JQVMap -->\r\n");
      out.write("<script src=\"plugins/jqvmap/jquery.vmap.min.js\"></script>\r\n");
      out.write("<script src=\"plugins/jqvmap/maps/jquery.vmap.usa.js\"></script>\r\n");
      out.write("<script src=\"plugins/datatables/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script src=\"plugins/datatables-bs4/js/dataTables.bootstrap4.min.js\"></script>\r\n");
      out.write("<script src=\"plugins/datatables-responsive/js/dataTables.responsive.min.js\"></script>\r\n");
      out.write("<script src=\"plugins/datatables-responsive/js/responsive.bootstrap4.min.js\"></script>\r\n");
      out.write("<!-- jQuery Knob Chart -->\r\n");
      out.write("<script src=\"plugins/jquery-knob/jquery.knob.min.js\"></script>\r\n");
      out.write("<!-- daterangepicker -->\r\n");
      out.write("<script src=\"plugins/moment/moment.min.js\"></script>\r\n");
      out.write("<script src=\"plugins/daterangepicker/daterangepicker.js\"></script>\r\n");
      out.write("<!-- Tempusdominus Bootstrap 4 -->\r\n");
      out.write("<script src=\"plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n");
      out.write("<!-- Summernote -->\r\n");
      out.write("<script src=\"plugins/summernote/summernote-bs4.min.js\"></script>\r\n");
      out.write("<!-- overlayScrollbars -->\r\n");
      out.write("<script src=\"plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js\"></script>\r\n");
      out.write("<!-- AdminLTE App -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"dist/js/adminlte.js\"></script>\r\n");
      out.write("<!-- AdminLTE dashboard demo (This is only for demo purposes) -->\r\n");
      out.write("<script src=\"dist/js/pages/dashboard.js\"></script>\r\n");
      out.write("<!-- AdminLTE for demo purposes -->\r\n");
      out.write("<script src=\"dist/js/demo.js\"></script>\r\n");
      out.write("<script src=\"../../plugins/inputmask/min/jquery.inputmask.bundle.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  var select1 = document.getElementById(\"select1\");\r\n");
      out.write("  var select2 = document.getElementById(\"select2\");\r\n");
      out.write("\r\n");
      out.write("  // İlk kutudan seçenek seçildiğinde senkronize et\r\n");
      out.write("  select1.addEventListener(\"change\", function() {\r\n");
      out.write("    var selectedOptions = Array.from(select1.selectedOptions);\r\n");
      out.write("\r\n");
      out.write("    selectedOptions.forEach(function(option) {\r\n");
      out.write("      select2.appendChild(option);\r\n");
      out.write("      option.selected = false;\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  // İkinci kutudan seçenek seçildiğinde senkronize et\r\n");
      out.write("  select2.addEventListener(\"change\", function() {\r\n");
      out.write("    var selectedOptions = Array.from(select2.selectedOptions);\r\n");
      out.write("\r\n");
      out.write("    selectedOptions.forEach(function(option) {\r\n");
      out.write("      select1.appendChild(option);\r\n");
      out.write("      option.selected = false;\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap 4 -->\r\n");
      out.write("\r\n");
      out.write("<!-- DataTables -->\r\n");
      out.write("\r\n");
      out.write("<!-- AdminLTE App -->\r\n");
      out.write("\r\n");
      out.write("<!-- AdminLTE for demo purposes -->\r\n");
      out.write("\r\n");
      out.write("<!-- page script -->\r\n");
      out.write("<script>\r\n");
      out.write("  $(function () {\r\n");
      out.write("    $(\"#example1\").DataTable({\r\n");
      out.write("      \"responsive\": true,\r\n");
      out.write("      \"autoWidth\": false,\r\n");
      out.write("    });\r\n");
      out.write("    $('#example2').DataTable({\r\n");
      out.write("      \"paging\": true,\r\n");
      out.write("      \"lengthChange\": false,\r\n");
      out.write("      \"searching\": true,\r\n");
      out.write("      \"ordering\": true,\r\n");
      out.write("      \"info\": true,\r\n");
      out.write("      \"autoWidth\": false,\r\n");
      out.write("      \"responsive\": true,\r\n");
      out.write("      \"language\": {\r\n");
      out.write("          \"url\": \"tr.json\"\r\n");
      out.write("        }\r\n");
      out.write("      \r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("  <script>\r\n");
      out.write("    function confirmDelete() {\r\n");
      out.write("        // Bootstrap modal for confirmation dialog\r\n");
      out.write("        var confirmationModal = `\r\n");
      out.write("            <div class=\"modal fade\" id=\"deleteConfirmationModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"deleteConfirmationModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("                <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("                    <div class=\"modal-content\">\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                            <h5 class=\"modal-title\" id=\"deleteConfirmationModalLabel\">Kullanıcıyı Sil</h5>\r\n");
      out.write("                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                                <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-body\">\r\n");
      out.write("                            Kullanıcıyı silmek istediğinize emin misiniz?\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-footer\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">İptal</button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger\" onclick=\"deleteUser()\">Sil</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        `;\r\n");
      out.write("\r\n");
      out.write("        // Append modal to the document body\r\n");
      out.write("        document.body.insertAdjacentHTML('beforeend', confirmationModal);\r\n");
      out.write("\r\n");
      out.write("        // Show the confirmation modal\r\n");
      out.write("        $('#deleteConfirmationModal').modal('show');\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function deleteUser() {\r\n");
      out.write("        // Perform delete operation here\r\n");
      out.write("        // This function will be called when the user confirms the deletion\r\n");
      out.write("        // You can add your code to delete the user from the system\r\n");
      out.write("\r\n");
      out.write("        // After successful deletion, you may redirect the user or update the table accordingly\r\n");
      out.write("\r\n");
      out.write("        // Close the confirmation modal\r\n");
      out.write("        $('#deleteConfirmationModal').modal('hide');\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
