/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.8
<<<<<<< HEAD
 * Generated at: 2023-07-24 13:47:05 UTC
=======
 * Generated at: 2023-07-24 13:44:51 UTC
>>>>>>> 7fd0b9eaae8ed87a85731764508a663b983da08b
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.example.example.DataBase.Rol;
import java.util.List;

public final class kayitol_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.example.example.DataBase.Rol");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<Rol> roles = Rol.getAllRoles();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- Designined by CodingLab - youtube.com/codinglabyt -->\r\n");
      out.write("<html lang=\"en\" dir=\"ltr\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title> Responsive Registration Form | CodingLab </title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/regg.css\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\">\r\n");
      out.write("     <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("   </head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"title\">KAYIT OL</div>\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("      <form action=\"kayitol\" method=\"post\">\r\n");
      out.write("        <div class=\"user-details\">\r\n");
      out.write("          <div class=\"input-box\">\r\n");
      out.write("            <span class=\"details\">İsim</span>\r\n");
      out.write("            <input type=\"text\" placeholder=\"Enter your name\" name=\"username\" required>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"input-box\">\r\n");
      out.write("            <span class=\"details\">Soyad</span>\r\n");
      out.write("            <input type=\"text\" placeholder=\"Enter your username\" name=\"surname\" required>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"input-box\">\r\n");
      out.write("            <span class=\"details\">Tc Kimlik Numarası</span>\r\n");
      out.write("            <input type=\"text\" placeholder=\"Confirm your password\" name=\"identity\"  maxlength=\"11\" minlength=\"11\" oninput=\"this.value = this.value.replace(/[^0-9]/g, '')\" required>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"input-box\">\r\n");
      out.write("            <span class=\"details\">Email</span>\r\n");
      out.write("            <input type=\"text\" placeholder=\"Enter your email\" name=\"email\" required>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"input-box\">\r\n");
      out.write("            <span class=\"details\">Telefon Numarası</span>\r\n");
      out.write("			<input type=\"tel\" placeholder=\"Enter your number\" name=\"number\" oninput=\"this.value = this.value.replace(/[^0-9]/g, '')\" maxlength=\"11\" minlength=\"11\" required>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"input-box\">\r\n");
      out.write("            <span class=\"details\">Parola</span>\r\n");
      out.write("            <input type=\"password\" placeholder=\"Enter your password\" name=\"password\" required>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"input-box\">\r\n");
      out.write("            <span class=\"details\">Parola Onay</span>\r\n");
      out.write("            <input type=\"password\" placeholder=\"Confirm your password\" name=\"password2\" required>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"input-box\">\r\n");
      out.write("            <span class=\"details\">Doğum Tarihi</span>\r\n");
      out.write("            <input type=\"date\" placeholder=\"Confirm your password\" name=\"date\" required>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"gender-details\">\r\n");
      out.write("          <input type=\"radio\" name=\"gender\" value=\"Erkek\" id=\"dot-1\">\r\n");
      out.write("          <input type=\"radio\" name=\"gender\" value=\"Kadın\" id=\"dot-2\">\r\n");
      out.write("          <input type=\"radio\" name=\"gender\" value=\"Diger\" id=\"dot-3\">\r\n");
      out.write("          <span class=\"gender-title\">Cinsiyet</span>\r\n");
      out.write("          <div class=\"category\">\r\n");
      out.write("            <label for=\"dot-1\">\r\n");
      out.write("            <span class=\"dot  \"></span>\r\n");
      out.write("            <span class=\"gender\">Erkek</span>\r\n");
      out.write("          </label>\r\n");
      out.write("          <label for=\"dot-2\">\r\n");
      out.write("            <span class=\"dot two\"></span>\r\n");
      out.write("            <span class=\"gender\">Kadın</span>\r\n");
      out.write("          </label>\r\n");
      out.write("          <label for=\"dot-3\">\r\n");
      out.write("            <span class=\"dot three\"></span>\r\n");
      out.write("            <span class=\"gender\">Diger</span>\r\n");
      out.write("            </label>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("                  <div>\r\n");
      out.write("				  <select name=\"Cars1\" size=\"5\" id=\"cars1\" class=\"form-control\">\r\n");
      out.write("				    ");
 for (Rol role : roles) { 
      out.write("\r\n");
      out.write("				      <option value=\"");
      out.print( role.getId() );
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print( role.getRoleName() );
      out.write("</option>\r\n");
      out.write("				    ");
 } 
      out.write("\r\n");
      out.write("				  </select>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"col-md-6\">\r\n");
      out.write("        <select name=\"Cars2\" size=\"5\" id=\"cars2\" class=\"form-control\" multiple>\r\n");
      out.write("        </select>\r\n");
      out.write("        </div>\r\n");
      out.write("      <script>\r\n");
      out.write("      document.getElementById(\"cars1\").addEventListener(\"change\", function() {\r\n");
      out.write("        var selected = this.options[this.selectedIndex];\r\n");
      out.write("        document.getElementById(\"cars2\").appendChild(selected);\r\n");
      out.write("      }); \r\n");
      out.write("      document.getElementById(\"cars2\").addEventListener(\"change\", function() {\r\n");
      out.write("        var selected = this.options[this.selectedIndex];\r\n");
      out.write("        document.getElementById(\"cars1\").appendChild(selected);\r\n");
      out.write("      }); \r\n");
      out.write("      </script>\r\n");
      out.write("        <div class=\"button\">\r\n");
      out.write("          <input type=\"submit\" value=\"Kayıt Ol\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
